### ISSUE TITLE
把数据库里面内容读取后在网页上显示一般采用什么方法？

### ISSUE THREAD

**Issue by xugaodong** [daxiazilong/vs-git-resolves#12]
把数据库（mysql）里面内容读取后在网页上显示一般采用什么方法？

**Comment by daxiazilong** [comment]
兄弟，这个issuses的目的是为了展示某些问题的解决方案而不是提问题的。
读取数据库里的内容之后，看你用的啥语言咯，把对应的结果展示到文件里就行。
